# Generated by Django 4.2 on 2023-04-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_news_date_alter_news_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=128)),
                ('tel', models.CharField(max_length=50)),
                ('massage', models.TextField()),
                ('is_trash', models.BooleanField(default=False)),
                ('is_view', models.BooleanField(default=False)),
                ('contacted', models.BooleanField(default=False)),
            ],
        ),
    ]
