# Generated by Django 4.2 on 2023-04-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='trash',
            field=models.BooleanField(default=True),
        ),
    ]
